name: Build NuGet V3 Catalog DB

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # - name: Build PROD DB
    #   run: dotnet run -- build-db --db-path artifacts/nuget-prod-commits.db --catalog-index https://api.nuget.org/v3/catalog0/index.json
    - name: Build INT DB
      run: dotnet run -- build-db --db-path artifacts/nuget-int-commits.db --catalog-index https://apiint.nugettest.org/v3/catalog0/index.json
    # - name: Build DEV DB
    #   run: dotnet run -- build-db --db-path artifacts/nuget-dev-commits.db --catalog-index https://apidev.nugettest.org/v3/catalog0/index.json
    - name: Upload INT DB
      uses: actions/upload-artifact@v4
      with:
        name: nuget-int-commits
        path: artifacts/nuget-int-commits.db
