name: Build NuGet V3 Catalog DB

on:
  workflow_dispatch:
  schedule:
    - cron: '44 4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Build PROD DB
      run: dotnet run -- build-db --db-path artifacts/nuget-prod-catalog.db --catalog-index https://api.nuget.org/v3/catalog0/index.json
    - name: Upload PROD DB
      uses: actions/upload-artifact@v4
      with:
        name: nuget-prod-catalog
        path: artifacts/nuget-prod-catalog.db
        retention-days: 3
        compression-level: 9
        if-no-files-found: error

    - name: Build INT DB
      run: dotnet run -- build-db --db-path artifacts/nuget-int-catalog.db --catalog-index https://apiint.nugettest.org/v3/catalog0/index.json
    - name: Upload INT DB
      uses: actions/upload-artifact@v4
      with:
        name: nuget-int-catalog
        path: artifacts/nuget-int-catalog.db
        retention-days: 3
        compression-level: 9
        if-no-files-found: error

    - name: Build DEV DB
      run: dotnet run -- build-db --db-path artifacts/nuget-dev-catalog.db --catalog-index https://apidev.nugettest.org/v3/catalog0/index.json
    - name: Upload DEV DB
      uses: actions/upload-artifact@v4
      with:
        name: nuget-dev-catalog
        path: artifacts/nuget-dev-catalog.db
        retention-days: 3
        compression-level: 9
        if-no-files-found: error
